# ALL STRINGS IN THIS CONFIG USE MINI MESSAGE FORMAT
# https://docs.advntr.dev/minimessage/format.html
debug: false
reloadDatapacks: false

chat:
  enabled: false

    # variables:
    # - <prefix> - requires Vault
    # - <suffix> - requires Vault
    # - <name>
    # - <message>
  format: "<name>: <message>"
  # in seconds
  cooldown: 3
  cooldownMessage: "<red>Please wait <cooldown> seconds before chatting again"

  filterWords: true
  filteredWords:
    - "shit"
    - "5hit"

  format-urls: true
  emojis-enabled: true
  addEmojisToCustomChatCompletions: true
  emojis:
    ":skull:": "‚ò†"
    ":smile:": "‚ò∫"
    ":frown:": "‚òπ"
    ":heart:": "<red>‚ù§</red>"
    ":fire:": "<gold>üî•</gold>"
    ":(": "‚òπ"
    ":)": "‚ò∫"

connectionMessages:
  modifyConnectionMessages: true

  # - <prefix> - requires Vault
  # - <suffix> - requires Vault
  # - <name>
  # - <join-number> - only available in firstJoinMessage
  firstJoinMessage: "<yellow><name> joined the game for the first time! [#<join-number>]"
  joinMessage: "<yellow><name> joined the game"
  quitMessage: "<yellow><name> left the game"

chats:
  enabled: true
  format: "<chat-name> <dark_gray>¬ª<white> <prefix><name><white>: <message>"
  globalChannelName: "<yellow>Global</yellow>"
  chatChannelIgnored: "<red>Cannot chat in channel <channel> because you've toggled it off!"
  customChats:
    staff:
      name: "<gold>Staff Chat</gold>"
      # - optional fields
      permission: "potatoessentials.channels.examplestaff"
      command: "sc"
      cooldown: 0
      # -
    #vip:
    #  name: "<green>VIP Chat"
    ## - optional fields
    #  permission: "potatoessentials.chats.examplevip"
    #  command: "vc"
    #  cooldown: 0 # in seconds

serverLinks:
  enabled: false
  serverLinks:
    example:
      name: "<rainbow>Test Example Thingy"
      # requires the 'https://' at the start of the string
      url: "https://thatpotato.dev/PotatoEssentials"

serverList:
  motdEnabled: false
  motd:
    - "<rainbow>Example Line 1"
    - "<rainbow>Example Line 2"
  hoverInfoEnabled: false
  # gradients don't work for this and IDK y
  hoverInfo:
    - "<aqua>Example 1"
    - "<red>Example 2: <blue>fr"

commands:
  message:
    enabled: true
      # variables:
      # - <receiver-prefix> - requires Vault
      # - <receiver-suffix> - requires Vault
      # - <sender-prefix> - requires Vault
      # - <sender-suffix  - requires Vault
      # - <receiver>
      # - <sender>
      # - <message>
    sender: "<gold>You <gray>¬ª</gray> <receiver><reset>: <message>"
    receiver: "<gold><sender> <gray>¬ª</gray> You<reset>: <message>"

    messagesDisabled: "<red><receiver>'s messages are disabled"

  messagetoggle:
    enabled: true
    toggledOff: "<gray>Private Messages have been<red> Disabled"
    toggledOn: "<gray>Private Messages have been<green> Enabled"
  reply:
    enabled: true
    noReply: "<red>You don't have anyone to reply to!"
  socialspy:
    enabled: true
    socialSpyEnabled: "<gray>[<gold>SocialSpy<gray>] <green>Enabled"
    socialSpyDisabled: "<gray>[<gold>SocialSpy<gray>] <red>Disabled"
    # same vars as /message
    message: "<gray>[<gold>SS</gold>] ¬ª <yellow><sender></yellow> -> <yellow><receiver></yellow>:</gray> <message>"
  broadcast:
    enabled: true
    message: "<newline>  <dark_gray>[<bold><red>SERVER ANNOUNCEMENT</red></bold>]<white> <message><newline>"
  tp:
    tpall-enabled: true
    tphere-enabled: true
    teleported-message: "<gray>You have been Teleported by <yellow><teleporter>"
    teleporter-message: "<gray>You have Teleported <yellow><teleported></yellow> to <yellow>Yourself"
  enchant:
    enabled: true
    message: "<gray>Applied<yellow> <enchantment></yellow> to<yellow> <target></yellow> held item"
  feed:
    enabled: true
    message: "<gray>Successfully fed<yellow> <target>"
  back:
    enabled: true
    message: "<gray>You have teleported to <yellow>your <gray>previous location"
  flyspeed:
    enabled: true
  gamemode:
    enabled: true
  heal:
    enabled: true
  hunger:
    enabled: true
  invsee:
    enabled: true
  ping:
    enabled: true
    pingMessage: "<yellow><player><gray>'s ping is <yellow><ping>"
  smite:
    enabled: true
    smiteMessage: "<gray>Smiting <yellow><targets>"
  vanish:
    enabled: true
    vanishMsg: "<yellow><player><gray> is now in vanish."
    unvanishMsg: "<player><gray> is no longer in vanish."
  clearinventory:
    enabled: true
    clearInventory: "<gray>Cleared<yellow> <target></yellow>'s Inventory"
  warp:
    enabled: true
    warpWarp: "<gray>Warping to <yellow><warp-name>"
    warpNotSet: "<red>Warp<yellow> <warp-name><red> is not set!"
  setwarp:
    enabled: true
    warpExists: "<red>Warp <warp-name> already exists!"
    warpSet: "<gray>Set Warp <yellow>'<warp-name>'</yellow> to<yellow> <location>"
  deletewarp:
    enabled: true
    warpDeleted: "<gray>Successfully <red>deleted</red> Warp<yellow> '<warp-name>'"
  mutechat:
    enabled: true
    mute: "<red>Chat muted by <yellow><sender>"
    unmute: "<green>Chat unmuted by <yellow><sender>"
  sudo:
    enabled: true
    say-message: "<gray>Making<yellow> <sudoed-players><gray> say: '<yellow><input></yellow>'"
    command-message: "<gray>Making<yellow> <sudoed-players><gray> execute: '<yellow><input></yellow>'"
  uptime:
    enabled: true
    message: "<aqua><b>Uptime</b>: <gold><uptime>"
  channel:
    enabled: true
    chatChannelChange: "<yellow>Chat channel</yellow><gray> set to </gray><chat-name>"
    chatNotFound: "<red>Chat <chat-name> not found"
    channelChangeIgnored: "<red>Cannot switch channel to <channel> because you've toggled it off!"
  togglechannel:
    enabled: true
    toggledOff: "<gray>Messages for channel '<yellow><channel></yellow>' have been <red>Disabled"
    toggledOn: "<gray>Messages for channel '<yellow><channel></yellow>' have been <green>Enabled"
    toggledCurrentChannel: "<gray>Toggled current channel, moved to <global>"
    toggleGlobal: "<red>Cannot toggle <global> channel"
  kit:
    enabled: true
    emptyInventory: "<red>You cannot create a kit with an empty inventory!"
    kitCreate: "<green>Created kit '<kit-name>'"
    kitNotFound: "<red>Kit with name '<kit-name>' does not exist!"
    kitAlreadyExists: "<red>A kit with the name '<kit-name>' already exists!"
    kitDelete: "<red>Deleted kit '<kit-name>'"
    kitGiveTo: "<green>Gave kit '<kit-name>' to <target>"
  clearchat:
    enabled: true
    message: "<green><name> cleared the chat"
  skin:
    enabled: true
    skinSet: "<green>Set skin to '<skin>'"
    skinNotFound: "<red>Skin not found!"
  skull:
    enabled: true
  troll:
    enabled: false
    attemptCrashSelf: "<red>You cannot crash yourself!"
    crash: "<gray>Crashing <yellow><target>"
    demoSingle: "<gray>Showing demo screen to <yellow><target>"
    demoMany: "<gray>Showing demo screen to <yellow><count> Players"
  teleportcenter:
    enabled: true